Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
events = boc.get_ophys_experiment_events(ophys_experiment_id=session_id)
------------------

----- stderr -----
2023-08-14 22:57:30,206 allensdk.api.api.retrieve_file_over_http INFO     Downloading URL: http://api.brain-map.org/api/v2/well_known_file_download/739721211
----- stderr -----
2023-08-14 22:57:32,120 allensdk.api.api.retrieve_file_over_http ERROR    Couldn't retrieve file /root/data/allen-brain-observatory/visual-coding-2p/ophys_experiment_events/501559087_events.npz from http://api.brain-map.org/api/v2/well_known_file_download/739721211
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/api/api.py:443[0m, in [0;36mstream_file_over_http[0;34m(url, file_path, timeout)[0m
[1;32m    442[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m(file_path, [38;5;124m'[39m[38;5;124mwb[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m fil:
[0;32m--> 443[0m     [43mstream[49m[38;5;241;43m.[39;49m[43mstream_response_to_file[49m[43m([49m[43mresponse[49m[43m,[49m[43m [49m[43mpath[49m[38;5;241;43m=[39;49m[43mfil[49m[43m)[49m

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/requests_toolbelt/downloadutils/stream.py:171[0m, in [0;36mstream_response_to_file[0;34m(response, path, chunksize)[0m
[1;32m    170[0m [38;5;28;01mfor[39;00m chunk [38;5;129;01min[39;00m response[38;5;241m.[39miter_content(chunk_size[38;5;241m=[39mchunksize):
[0;32m--> 171[0m     [43mfd[49m[38;5;241;43m.[39;49m[43mwrite[49m[43m([49m[43mchunk[49m[43m)[49m
[1;32m    173[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m pre_opened:

[0;31mOSError[0m: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[16], line 1[0m
[0;32m----> 1[0m events [38;5;241m=[39m [43mboc[49m[38;5;241;43m.[39;49m[43mget_ophys_experiment_events[49m[43m([49m[43mophys_experiment_id[49m[38;5;241;43m=[39;49m[43msession_id[49m[43m)[49m

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/core/brain_observatory_cache.py:639[0m, in [0;36mBrainObservatoryCache.get_ophys_experiment_events[0;34m(self, ophys_experiment_id, file_name)[0m
[1;32m    619[0m [38;5;250m[39m[38;5;124;03m"""Download the npz events file for an ophys_experiment if it hasn't[39;00m
[1;32m    620[0m [38;5;124;03malready been downloaded and return the events array.[39;00m
[1;32m    621[0m 
[0;32m   (...)[0m
[1;32m    633[0m [38;5;124;03m    [N_cells,N_times] array of events.[39;00m
[1;32m    634[0m [38;5;124;03m"""[39;00m
[1;32m    635[0m file_name [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_cache_path(
[1;32m    636[0m     file_name, [38;5;28mself[39m[38;5;241m.[39mEVENTS_DATA_KEY, ophys_experiment_id
[1;32m    637[0m )
[0;32m--> 639[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mapi[49m[38;5;241;43m.[39;49m[43msave_ophys_experiment_event_data[49m[43m([49m
[1;32m    640[0m [43m    [49m[43mophys_experiment_id[49m[43m,[49m[43m [49m[43mfile_name[49m[43m,[49m[43m [49m[43mstrategy[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mlazy[39;49m[38;5;124;43m"[39;49m
[1;32m    641[0m [43m[49m[43m)[49m
[1;32m    643[0m [38;5;28;01mreturn[39;00m np[38;5;241m.[39mload(file_name, allow_pickle[38;5;241m=[39m[38;5;28;01mFalse[39;00m)[[38;5;124m"[39m[38;5;124mev[39m[38;5;124m"[39m]

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/api/warehouse_cache/cache.py:661[0m, in [0;36mcacheable.<locals>.decor.<locals>.w[0;34m(*args, **kwargs)[0m
[1;32m    658[0m [38;5;28;01mif[39;00m decor[38;5;241m.[39mpost [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m [38;5;124m'[39m[38;5;124mpost in kwargs[39m[38;5;124m'[39m:
[1;32m    659[0m     kwargs[[38;5;124m'[39m[38;5;124mpost[39m[38;5;124m'[39m] [38;5;241m=[39m decor[38;5;241m.[39mpost
[0;32m--> 661[0m result [38;5;241m=[39m [43mCache[49m[38;5;241;43m.[39;49m[43mcacher[49m[43m([49m[43mfunc[49m[43m,[49m
[1;32m    662[0m [43m                      [49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m
[1;32m    663[0m [43m                      [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    664[0m [38;5;28;01mreturn[39;00m result

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/api/warehouse_cache/cache.py:387[0m, in [0;36mCache.cacher[0;34m(fn, *args, **kwargs)[0m
[1;32m    385[0m         writer(path, data)
[1;32m    386[0m     [38;5;28;01melse[39;00m:
[0;32m--> 387[0m         data [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    389[0m [38;5;28;01mif[39;00m reader:
[1;32m    390[0m     data [38;5;241m=[39m reader(path)

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/api/queries/brain_observatory_api.py:493[0m, in [0;36mBrainObservatoryApi.save_ophys_experiment_event_data[0;34m(self, ophys_experiment_id, file_name)[0m
[1;32m    484[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m(
[1;32m    485[0m         [38;5;124m"[39m[38;5;124mophys experiment [39m[38;5;132;01m%d[39;00m[38;5;124m has no events file[39m[38;5;124m"[39m [38;5;241m%[39m ophys_experiment_id
[1;32m    486[0m     )
[1;32m    487[0m [38;5;28mself[39m[38;5;241m.[39m_log[38;5;241m.[39mwarning(
[1;32m    488[0m     [38;5;124m"[39m[38;5;124mDownloading ophys_experiment [39m[38;5;132;01m%d[39;00m[38;5;124m events file. This can take [39m[38;5;124m"[39m
[1;32m    489[0m     [38;5;124m"[39m[38;5;124msome time.[39m[38;5;124m"[39m
[1;32m    490[0m     [38;5;241m%[39m ophys_experiment_id
[1;32m    491[0m )
[0;32m--> 493[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mretrieve_file_over_http[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mapi_url[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[43mfile_url[49m[43m,[49m[43m [49m[43mfile_name[49m[43m)[49m

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/api/api.py:323[0m, in [0;36mApi.retrieve_file_over_http[0;34m(self, url, file_path, zipped)[0m
[1;32m    321[0m         stream_zip_directory_over_http(url, os[38;5;241m.[39mpath[38;5;241m.[39mdirname(file_path))
[1;32m    322[0m     [38;5;28;01melse[39;00m:
[0;32m--> 323[0m         [43mstream_file_over_http[49m[43m([49m[43murl[49m[43m,[49m[43m [49m[43mfile_path[49m[43m)[49m
[1;32m    325[0m [38;5;28;01mexcept[39;00m exceptions[38;5;241m.[39mStreamingError [38;5;28;01mas[39;00m e:
[1;32m    326[0m     [38;5;28mself[39m[38;5;241m.[39m_file_download_log[38;5;241m.[39merror([38;5;124m"[39m[38;5;124mCouldn[39m[38;5;124m'[39m[38;5;124mt retrieve file [39m[38;5;132;01m%s[39;00m[38;5;124m from [39m[38;5;132;01m%s[39;00m[38;5;124m (streaming).[39m[38;5;124m"[39m [38;5;241m%[39m (file_path,url))

File [0;32m/opt/envs/allensdk/lib/python3.8/site-packages/allensdk/api/api.py:443[0m, in [0;36mstream_file_over_http[0;34m(url, file_path, timeout)[0m
[1;32m    441[0m response[38;5;241m.[39mraise_for_status()
[1;32m    442[0m [38;5;28;01mwith[39;00m [38;5;28mopen[39m(file_path, [38;5;124m'[39m[38;5;124mwb[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m fil:
[0;32m--> 443[0m     stream[38;5;241m.[39mstream_response_to_file(response, path[38;5;241m=[39mfil)

[0;31mOSError[0m: [Errno 28] No space left on device

